config/routes.rb
Openportal::Application.routes.draw do
  resources :issues

  resources :organizations

  resources :dashboard

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :users

  get '/github_pull_info', to: 'issues#github_pull_info'

  get "welcome/index"

  root 'welcome#index'

  

  resources :users, only: [:index, :new, :create]
  resources :users, path: "", except: [:index, :new, :create]
end

app/models/issue.rb
class Issue < ActiveRecord::Base
	  belongs_to :organization
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render action: 'show', status: :created, location: @issue }
      else
        format.html { render action: 'new' }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :no_content }
    end
  end

  def github_pull_info

    #This is for rails repository
    @issues_from_site = JSON.parse(RestClient.get("https://api.github.com/repos/rails/rails/issues?client_id=#{ENV["CLIENT_ID"]}&client_secret=#{ENV["CLIENT_SECRET"]}"))
    
    @events = JSON.parse(RestClient.get("https://api.github.com/repos/rhintz42/scpd-scraper/events?client_id=#{ENV["CLIENT_ID"]}&client_secret=#{ENV["CLIENT_SECRET"]}"))
    
    @latest_repository = JSON.parse(RestClient.get("https://api.github.com/repos/rhintz42/scpd-scraper/git/refs/heads/master?client_id=#{ENV["CLIENT_ID"]}&client_secret=#{ENV["CLIENT_SECRET"]}"))
    
    @issues = []

    @issues_from_site.each do |i|
      issue = Issue.new
      issue[:issue_id] = i["number"]
      issue[:status] = i["state"]
      issue[:description] = i["title"]
      issue[:url] = i["url"]
      issue[:organization_id] =  1 #params["organization_id"]

      #take out
      issue.level = Random.rand(0...5)
      
   
      issue.save

      @issues << issue
    end

    respond_to do |format|
      format.html
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:organization_id, :name, :url, :issue_id, :status, :level, :description)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :organization_id %><br>
    <%= f.number_field :organization_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :issue_id %><br>
    <%= f.number_field :issue_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/github_pull_info.html.erb
<%= @issues %>

app/views/issues/index.html.erb
<h1>Listing issues</h1>

<table>
  <thead>
    <tr>
      <th>Organization</th>
      <th>Name</th>
      <th>Url</th>
      <th>Issue</th>
      <th>Status</th>
      <th>Level</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.organization_id %></td>
        <td><%= issue.name %></td>
        <td><%= issue.url %></td>
        <td><%= issue.issue_id %></td>
        <td><%= issue.status %></td>
        <td><%= issue.level %></td>
        <td><%= issue.description %></td>
        <td><%= link_to 'Show', issue %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<h1>New issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Organization:</strong>
  <%= @issue.organization_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @issue.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @issue.url %>
</p>

<p>
  <strong>Issue:</strong>
  <%= @issue.issue_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @issue.status %>
</p>

<p>
  <strong>Level:</strong>
  <%= @issue.level %>
</p>

<p>
  <strong>Description:</strong>
  <%= @issue.description %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>