config/routes.rb
Openportal::Application.routes.draw do
  resources :issues

  resources :organizations

  resources :dashboard

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :users

  get '/github_pull_info', to: 'issues#github_pull_info'

  get "welcome/index"

  root 'welcome#index'

  

  resources :users, only: [:index, :new, :create]
  resources :users, path: "", except: [:index, :new, :create]
end

app/views/layouts/_header_anon.html.erb
<div class="header-container">
    <div class="header-anon">
        <div class="header-left-anon">
            <div class="header-logo">
                OpP
            </div>
        </div>
        <div class="header-middle-anon">
            <div class="header-search-container">
              <div class="header-search">
                <form action="#">
                  <input type="search" name="s" placeholder="Search or type a command" />
                </form>
              </div>
            </div>
            <div class="header-tab-list-container">
                <a href="#">
                  <div class="header-tab-container">
                      <div class="header-tab">
                          Features
                      </div>
                  </div>
                </a>
                <%= link_to organizations_path do %>
                  <div class="header-tab-container">
                      <div class="header-tab">
                          Organizations
                      </div>
                  </div>
                <% end %>
                <a href="#">
                  <div class="header-tab-container">
                      <div class="header-tab">
                          People
                      </div>
                  </div>
                </a>
                <a href="#">
                  <div class="header-tab-container">
                      <div class="header-tab">
                          About
                      </div>
                  </div>
                </a>
            </div>
        </div>
        <div class="header-right-anon">
          <%= link_to login_path do %>
            <div class="header-login-container">
              Sign in
            </div>
          <% end %>
        </div>
    </div>
</div>

<div class="separator">
</div>

app/views/layouts/_header_signed_in.html.erb
<div class="header-container">
    <div class="header-anon">
        <div class="header-left-anon">
            <div class="header-logo">
                OpP
            </div>
        </div>
        <div class="header-middle-anon">
            <div class="header-search-container">
              <div class="header-search">
                <form action="#">
                  <input type="search" name="s" placeholder="Search or type a command" />
                </form>
              </div>
            </div>
            <div class="header-tab-list-container">
                <a href="#">
                  <div class="header-tab-container">
                      <div class="header-tab">
                          Features
                      </div>
                  </div>
                </a>
                <a href="#">
                  <div class="header-tab-container">
                      <div class="header-tab">
                          Organizations
                      </div>
                  </div>
                </a>
                <a href="#">
                  <div class="header-tab-container">
                      <div class="header-tab">
                          People
                      </div>
                  </div>
                </a>
                <a href="#">
                  <div class="header-tab-container">
                      <div class="header-tab">
                          About
                      </div>
                  </div>
                </a>
            </div>
        </div>
        <div class="header-right-anon">
          <%= link_to logout_path do %>
            <div class="header-login-container">
              logout
            </div>
          <% end %>
        </div>
    </div>
</div>

<div class="separator">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Openportal</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    <%= render "layouts/header_signed_in" %>
  <% else %>
    <%= render "layouts/header_anon" %>
  <% end %>
  <div class="under-header-main">
    <div class="container">
      <%= yield %>
    </div>
  </div>
</body>
</html>